### ISSUE TITLE
H&L (and backdeck trawl i think) qtquick controls version mismatch

### ISSUE THREAD

**Issue by SaOgaz-NOAA** [nwfsc-fram/pyFieldSoftware#141]
In the current state of the code at the point @jimfellows-NOAA and I grabbed it, there are several places in the qml files calling `import QtQuick.Controls 2.2`. The problem is Qt 5.7.1 only supports up to Controls 2.0: https://doc.qt.io/qt-5/qtquickcontrols-index.html.

I tried messing around to see if I could work around it, I installed an updated version of Qt in a separate env, then tried to add those qml libs with the QM2_LIB_IMPORT keyword. I also tried copying the folder for the version 2.2 into my working env. Neither of these attempts worked.

There do seem to be quite a few updates between controls 2.0 and 2.2, so this may end up being a problem on the tablets.  I think the next step is to get into the pilot plant and see if builds with 2.0 cause any issues.

**Comment by jimfellows-NOAA** [comment]
Just so I don't forget, here's how to reproduce at least one error this causes:

1. Launch main_hookandline_fpc (HookLogger)
2. Launch main_hookandline_hookmatrix
3. Click "All Sites", then click a site (e.g. Sixty Mile Bank)
4. Click "Hooks" on the next page
5. You then get an error message in the GUI:

![image](https://user-images.githubusercontent.com/57507677/91740292-f4d54d80-eb67-11ea-953c-0637fea7be28.png)

**Comment by SaOgaz-NOAA** [comment]
So @jimfellows-NOAA and I huddled on this this morning, and it appears that 5.9 is the way to go for the hook and line content. It also fixed that canvas save issue we were having, so I *think* our H&L builds are now working as expected!
