### ISSUE TITLE
Unable to insert first drop and angler on HookMatrix drops screen

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/pyFieldSoftware#157]
For whatever reason an operation record already exists in the SQLite db hookandline_fpc.db file for either an angler or drop, and the resulting error message pops up, preventing the user from starting the drop on the Drops screen.  @johnharms-NOAA you ever run into this with HookMatrix?:

![image](https://user-images.githubusercontent.com/57507677/95595977-a8501e00-0a01-11eb-8828-4d12d07fcc40.png)

Not sure if having this existing record in the db file exists in practice, but the code in Drops.py looks like its trying to handle the scenario but isn't doing it properly.  Here's what happens when you click the "Start" button in the code:

1. drops.insert_operation(drop_number) is called
2. code first tries to insert the drop record
3. It tries to catch an apsw.ConstraintError exception if the record exists
4. If caught the code then runs a select statement to grab the ID of the existing record

The xmlrpc.client package is returning the constraint error as a `<Fault 1: "<class 'UnboundLocalError'>:local variable 'results' referenced before assignment">` instead, not sure if this is a Python versioning issue (xmlrpc is a python base package).  This causes the code to skip to a generic exception rather than handling it correctly.

Possible fix, add in an or statement to catch the xmlrpc fault at lines 110 and 150 in insert_operation:

```python
import xmlrpc.client as xrc
...
if "apsw.ConstraintError" in str(ex) or isinstance(ex, xrc.Fault):
...
```

**Comment by SaOgaz-NOAA** [comment]
I wonder if this is one of those situations that never really happen on the boat, because they always finish out the drops for an area. Or if they don't they never go back to it in this software.

**Comment by johnharms-NOAA** [comment]
This error is not something I recall getting in the field - I have only seen it as we have been doing the recent testing and troubleshooting.  When it popped up, I got the impression it had to do with not being able to enter new drops in the Galley app (because we weren't connected to a live serial data feed), and hence, HookMatrix couldn't start timers for a drop that didn't exist in the main Galley database.

**Comment by SaOgaz-NOAA** [comment]
That's the guess @jimfellows-NOAA and I came to after taking another look at it last week.

**Comment by jimfellows-NOAA** [comment]
Fix committed to develop-hlmatrix branch.
