### ISSUE TITLE
Add new toolbar icons for all 3 HookLogger workstations

### ISSUE THREAD

**Issue by johnharms-NOAA** [nwfsc-fram/pyFieldSoftware#175]
To make it easier to differentiate among the three HookLogger apps when using them on the same machine (such as during testing), please use the following graphics for the apps:

For the Galley station:
![icons_pole 5](https://user-images.githubusercontent.com/60898545/98024008-8ce7f100-1dbc-11eb-859d-bc8f8ede193c.png)

For HookMatrix station:
![icons_hook 5](https://user-images.githubusercontent.com/60898545/98024039-98d3b300-1dbc-11eb-9f23-be3ef4605864.png)

For the Cutter station:
![icons_scalpel 5](https://user-images.githubusercontent.com/60898545/98024076-a1c48480-1dbc-11eb-80cf-6dec2170d91e.png)

**Comment by jimfellows-NOAA** [comment]
Icons added in to newly built apps on develop branches.

**Comment by johnharms-NOAA** [comment]
Sweet!

**Comment by jimfellows-NOAA** [comment]
Dropped builds in the Data/HookAndLine/Software folders if you wanna take a look.
