### ISSUE TITLE
Ask user if they're sure when selecting inactive ovary projects

### ISSUE THREAD

**Issue by jimfellows-NOAA** [nwfsc-fram/pyFieldSoftware#257]
As of 2021 "Ovary Section-FRAM" is the only ovary special project that should be used.  Need to add a warning asking if the user would like to continue if "Ovary Section-SWFSC" special project tag is selected and the "Assign & Print" button is then pressed:

![image](https://user-images.githubusercontent.com/57507677/132420616-695f1b2d-c6a6-4295-8913-0594512300a2.png)

**Comment by johnharms-NOAA** [comment]
Thanks Jim.  If possible, popping up a similar warning if "Whole Ovary-FRAM" or "Whole Ovary-SWFSC" is selected.  We aren't planning to collect whole ovaries this year, but I don't want to outright prohibit it...this is just to catch the instances where the cutter might be confused about what to select and selects something other than "Ovary Section-FRAM".

**Comment by jimfellows-NOAA** [comment]
Got it, thanks for clarifying, I'll aim to have it pop for both of the "Whole Ovary" sample options.

**Comment by jimfellows-NOAA** [comment]
Will be rebuilding Cutter Station this morning, with this included.  Workflow is:
1. User selects special project row in special tab
2. Clicks "Assign & Print Label"
3. If name of project is like "Whole Ovary" or equals "Ovary Section-SWFSC", dialog pops asking if they're sure
4. Clicking cancel does nothing, clicking Okay continues on to assign label and print tag

![image](https://user-images.githubusercontent.com/57507677/132550537-0dd0326a-2022-4ff0-9b62-34d81f79745b.png)
