### ISSUE TITLE
H&L: NotesDialog: Change button names to site note, drop note, hook note, gear note

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/pyFieldSoftware#78]

**Comment by johnharms-NOAA** [comment]
This may be the same as item #80

**Comment by SaOgaz-NOAA** [comment]
Hi @johnharms-NOAA, just to make sure i'm looking at the right thing... are those changes for the buttons at the top of this screen?

![image](https://user-images.githubusercontent.com/54552385/89832578-68111400-db14-11ea-9c9f-838e9323e11b.png)

**Comment by SaOgaz-NOAA** [comment]
Edit, I guess those aren't actually buttons...

**Comment by johnharms-NOAA** [comment]
Hi @SaOgaz-NOAA  - it might end up being easier to chat by phone as the various issues related to HookLogger's Notes functions are inter-related. Basically we need to be able to track a note that a user makes at any of the 3 workstations (Cutter, HookMatrix, and HookLogger/galley) and be able to know in which field of our final Access database that note should ultimately get stored. The levels are essentially hierarchical and go from Site>Drop>Angler>Hook>Fish>Specimen
Notes taken at the HookLogger workstation (virtually 100% of which pertain to the site level) are written as text to the SQLite database, so we are largely OK there. However, at the HookMatrix and Cutter stations, notes are taken by writing on the screen with a stylus or finger and the notes are stored as PNGs. Though the software does usually capture the appropriate hierarchical level, it's very buggy, there is no ability to edit or add to prior notes, and the PNG that gets written includes no useful information in its filename to tell you what site/angler/drop, etc. it applies to - so each note PNG has to be re-opened post-survey, read on the screen, and then cross-checked with the SQLite database to know where it should go in Access. I'm sure this is very confusing, so if a phone/video call will help, please email me and we can set something up.  Thank you!

**Comment by SaOgaz-NOAA** [comment]
Was able to make this change successfully, huzzah! Will apply same update to cutter station.

**Comment by johnharms-NOAA** [comment]
Excellent - thank you! Hopefully we will get some idea about whether we'll get access to the work area Victor is setting up so we can get the whole system set up with all 3 workstations and get some of these issues demonstrated in a real world setting.
