### ISSUE TITLE
Trawl: TowLogger: creeping wheelhouse computer clock (Fix)

### ISSUE THREAD

**Issue by ghost** [nwfsc-fram/pyFieldSoftware#96]
Wheelhouse comptuer clock creep issues in 2019 (some folks encountered this others did not). Make sure computer clock still updates from GPS or Sat compass every 5 mins. Would be great if we can use this code for HookLogger software, too! [WS - code was added May 2017]

**Comment by SaOgaz-NOAA** [comment]
Hmm, it looks like right now (in the repo copy of the code we pulled) it's set to once every half hour:

`self._frequency = 1800 #5 #3600       # TODO Todd Hay - Set back to 3600 (i.e. 1 hour updates) for deployment`

Does this timing seem to match what you guys have been seeing? I can set this to five minutes, but want to confirm that i'm editing the right part of the code.

**Comment by peterfrey-NOAA** [comment]
From what I can tell you are looking in the right place. However, I wonder if there are any unintended user consequences to having the time update more frequently (like I'm wondering why Todd was going to set it to an hour for deployment?) or if it would be just as fine and invisible if it sync'd every 5 minutes (which is what I already thought it did). Also, can you tell by what you are looking at what our 'sync' data stream is? I think when this software was originally designed we were sync'ing to our garmin gps, but in more recent years we've been using vessel SC50 sat compasses.

**Comment by SaOgaz-NOAA** [comment]
@peterfrey-NOAA I don't see any super obvious consequence to updating on the 5 minute time scale, but I guess that's the thing with this software and having unforseen consequences. We'll just have to get into the pilot plant with the change and see what happens. It's also possible we're working with an old version of that code?

As far as the sync data stream, the bits of code i'm finding seem to be able to handle both. So my best guess is that it figures that out from pinging what's connected, or some kind of configuration file I can't place.  Were you mostly curious about this, or have there been recent problems with that?

**Comment by peterfrey-NOAA** [comment]
Yeah, I agree, we'll have to just kick the tires on this one in the pilot plant once the world gets back to normal, but I imagine this will take care of whatever clock creep issues were occurring in 2019. I was just curious about the data stream, I don't think there have been any issues going from the garmin GPS's to the Sat compasses. Thanks!

**Comment by SaOgaz-NOAA** [comment]
Closing this for now... we'll see if it's working when tested.
